### ISSUE TITLE
Common Test execution warning on unhandled dependency

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [g-andrade/tls_certificate_check#1]
I'm getting this
```
tls_certificate_check_SUITE ==> {tc_user_skip,"Dependent on https://github.com/chromium/badssl.com/pull/443 being approved"}
```
but the linked dependency hasn't moved forward in a few months.

**Comment by g-andrade** [comment]
I've updated [chromium/443](https://github.com/chromium/badssl.com/pull/443) according to the reviewers' recommendations; let's see whether that gets things running again.

**Comment by paulo-ferraz-oliveira** [comment]
Has this moved on badssl.com?

**Comment by g-andrade** [comment]
The new subdomain [has been deployed](https://reversed-chain.badssl.com/), but it doesn't work as expected - neither on the browser nor on `tls_certificate_check`'s tests.

There's some problem yet to solve. A discussion was started, a few weeks ago, on [badssl.com/#443](https://github.com/chromium/badssl.com/pull/443) but it hasn't moved forwarded since.

**Comment by g-andrade** [comment]
In any case, something appears to have changed on OTP's internals and the remaining test cases now cover 100% of the code (OTP 23) - [`tls_certificate_check_chain:find_authority/1`](https://github.com/g-andrade/tls_certificate_check/blob/1.2.0/src/tls_certificate_check_chain.erl#L38-L53) (the successor of `tls_certificate_chain:find_authority/1` following #10) is now called.

Not sure whether there's still a need to explicitly cover the case of disorderly certificate chains, though.

**Comment by paulo-ferraz-oliveira** [comment]
That's fun.

**Comment by g-andrade** [comment]
Test case removed on 325fe07 since it would no longer have any effect on coverage.

**Comment by paulo-ferraz-oliveira** [comment]
👀
