### ISSUE TITLE
Do not hardcode records in authorities list

### ISSUE THREAD

**Issue by g-andrade** [g-andrade/tls_certificate_check#12]
[Here](https://github.com/g-andrade/tls_certificate_check/blob/master/src/tls_certificate_check_authorities.erl#L6871-L6872). If said record definitions change, that function will break.

Consider reintroducing `ct_expand` for that particular bit. Or perhaps leave it to `persistent_term`, whereupon the necessary processing would be done when the application boots.

**Comment by paulo-ferraz-oliveira** [comment]
And potentially arrange for a way for the certificates to be updated, too. That'd be nifty.

**Comment by g-andrade** [comment]
Fixed under `1.3.0`

**Comment by g-andrade** [comment]
> And potentially arrange for a way for the certificates to be updated, too. 

Some work was done and pushed into the `feature/auto-updates` branch; it's a complex problem with many potential security issues. I'll very possibly not go ahead with it.
