### ISSUE TITLE
Allow for consumer-provided CA store

### ISSUE THREAD

**Issue by g-andrade** [g-andrade/tls_certificate_check#14]
As per [my own plan back in 2020](https://elixirforum.com/t/tls-certificate-check-tls-ssl-certificate-verification-for-humans/31677/3?u=g-andrade), which as it stands I promptly forgot.

This issue will remind me of it.

**Comment by g-andrade** [comment]
The semantics of this feature would be weird ever since `tls_certificate_check` started bundling CAs / deprecating older releases with outdated bundles in Hex.

I.e. if one uses a custom CA-store, it's unreasonable that one day `rebar3` or `mix` start complaining that the version of `tls_certificate_check` in use is outdated - the CAs in use are not the bundled ones.

**Comment by filmor** [comment]
Do you have any concrete plans for this? Do you need help?

**Comment by g-andrade** [comment]
I never had the need for this feature, so no concrete plans. My availability for open source work is minimal nowadays, so yes, contributions are welcome 👍

**Comment by g-andrade** [comment]
I haven't tagged this yet as I'd like to rewrite a few things but haven't found the chance to do it.

**Comment by g-andrade** [comment]
Released under `1.17.0`
