### ISSUE TITLE
Lib is broken on rebar3 3.14.4

### ISSUE THREAD

**Issue by g-andrade** [g-andrade/tls_certificate_check#8]
No certificates are loaded (even though compilation succeeds.)

See [certifi PR #44](https://github.com/certifi/erlang-certifi/pull/44).

**Comment by paulo-ferraz-oliveira** [comment]
Also see https://github.com/certifi/erlang-certifi/issues/45 and potentially derived pull requests.

**Comment by g-andrade** [comment]
No longer a problem :)

**Comment by benoitc** [comment]
mmm
